server:
  port: 8081

spring:
#  data:
#    redis:
#      host: localhost
#      port: 6379
  redis:
    host: localhost
    port: 6379

backend:
  update-report-status-url: localhost:8080/v1/report/status

