version: '3'
services:
  report-app:
    image: report-app
    build:
      context: report
      dockerfile: Dockerfile
    links:
      - redis-server
    ports:
      - "8080:8080"
    environment:
      - "spring.data.redis.host=redis-server"
    networks:
      - queue-network

  image-processing-app:
    image: image-processing-app
    build:
      context: image-processing
      dockerfile: Dockerfile
    environment:
      - "spring.data.redis.host=redis-server"
      - "backend.update-report-status-url=http://report-app:8080/v1/report/status"
    links:
      - redis-server
    networks:
      - queue-network

  redis-server:
    image: redis:latest
    hostname: redis-server
#    ports:
#      - "6379:6379"
#      - "8001:8001"
#    environment:
#      - REDIS_REPLICATION_MODE=master
    networks:
      - queue-network

networks:
  queue-network: