version: '3'
services:
  redis-queue-app:
    image: redis-queue-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
    networks:
      - redis-queue

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - redis-queue

networks:
  redis-queue: